baseURL = "http://ajmalsiddiqui.me/"
languageCode = "en"
title = "Ajmal's Website"
theme = "noteworthy"

googleAnalytics = "UA-153877586-2"

enableRobotsTXT = true

[author]
    name = "Ajmal"

# These are for the dream theme
[params]
    description = "Coder, car/bike lover, polyglot."

    email = "ajmalsiddiqui21@gmail.com"
    twitter = "https://twitter.com/_ajmalsiddiqui"
    github = "https://github.com/ajmalsiddiqui"
    linkedin = "https://linkedin.com/in/ajmal-siddiqui"
    medium = "https://medium.com/@ajmalsiddiqui21"

[[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 1

[[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight = 2
