baseURL = "https://ajmalsiddiqui.me/"
languageCode = "en"
title = "Ajmal's Website"
theme = "noteworthy"

googleAnalytics = "G-WTZP328X14"

enableRobotsTXT = true

[author]
    name = "Ajmal"

# These are for the dream theme
[params]
    author = "Mohammed Ajmal Siddiqui"
    description = "Coder, car/bike lover, polyglot."

    mainSections = [ "blog", "ctf-writeups" ]

    resume = "https://drive.google.com/file/d/1x6EIpvlooDc7dT0rlyd1qcRH2qcnDPuZ/view"
    email = "ajmalsiddiqui21@gmail.com"
    twitter = "https://twitter.com/_ajmalsiddiqui"
    github = "https://github.com/ajmalsiddiqui"
    linkedin = "https://linkedin.com/in/ajmal-siddiqui"
    medium = "https://medium.com/@ajmalsiddiqui21"

[[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 1

[[menu.main]]
    identifier = "ctf-writeups"
    name = "CTF Write-Ups"
    url = "/ctf-writeups/"
    weight = 2

[[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 3

[[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight = 4
